INSERT INTO commits (stamp, user, details) VALUES (20171204123118, 'robin', '');
INSERT INTO elephants (num, name, calf_num, sex, birth, cw, age_capture, camp, alive, research, commits) VALUES (6844, 'Nan Nilar Test', null, 'F', '1904-11-30', 'captive', null, 'Mawlaik', 'Y', 'N', 11);
UPDATE elephants SET age_capture='50', commits='1,11' WHERE id=5995;
INSERT INTO elephants (num, name, calf_num, sex, birth, cw, age_capture, camp, alive, research, commits) VALUES (943, 'Bote Sonee', null, 'F', '1899-11-30', 'wild', '41', null, 'N', 'N', 11);
UPDATE elephants SET name='Po Dan', commits='1,11' WHERE id=6023;
INSERT INTO elephants (num, name, calf_num, sex, birth, cw, age_capture, camp, alive, research, commits) VALUES (112, 'Swea Site', null, 'M', '1898-11-30', 'wild', '54', null, 'N', 'N', 11);
INSERT INTO elephants (num, name, calf_num, sex, birth, cw, age_capture, camp, alive, research, commits) VALUES (6844, 'Nan Nilar Test', null, 'F', '1904-11-30', 'captive', null, 'Mawlaik', 'Y', 'N', 11);
UPDATE elephants SET age_capture='50', commits='1,11' WHERE id=5995;
INSERT INTO elephants (num, name, calf_num, sex, birth, cw, age_capture, camp, alive, research, commits) VALUES (943, 'Bote Sonee', null, 'F', '1899-11-30', 'wild', '41', null, 'N', 'N', 11);
UPDATE elephants SET name='Po Dan', commits='1,11' WHERE id=6023;
INSERT INTO elephants (num, name, calf_num, sex, birth, cw, age_capture, camp, alive, research, commits) VALUES (112, 'Swea Site', null, 'M', '1898-11-30', 'wild', '54', null, 'N', 'N', 11);
INSERT INTO elephants (num, name, calf_num, sex, birth, cw, age_capture, camp, alive, research, commits) VALUES (6844, 'Nan Nilar Test', null, 'F', '1904-11-30', 'captive', null, 'Mawlaik', 'Y', 'N', 11);
UPDATE elephants SET name='Toe Aye, Toe Ta Aye', commits='1,11' WHERE id=5988;
UPDATE elephants SET name='Shwe May, Shwe May Chips', commits='1,11' WHERE id=5993;
UPDATE elephants SET age_capture='50', commits='1,11' WHERE id=5995;
UPDATE elephants SET name='Ta Wor, Ta Wor Prout', commits='1,11' WHERE id=5998;
INSERT INTO elephants (num, name, calf_num, sex, birth, cw, age_capture, camp, alive, research, commits) VALUES (943, 'Bote Sonee', null, 'F', '1899-11-30', 'wild', '41', null, 'N', 'N', 11);
UPDATE elephants SET name='Po Dan', commits='1,11' WHERE id=6023;
INSERT INTO elephants (num, name, calf_num, sex, birth, cw, age_capture, camp, alive, research, commits) VALUES (112, 'Swea Site', null, 'M', '1898-11-30', 'wild', '54', null, 'N', 'N', 11);
